### ISSUE TITLE
Fix url error pipeline of automatic data collection

### ISSUE THREAD

**Issue by Ciertje** [course-dprep/team-project-team_1#11]
The current code works, but as i try to automate the retrieval i am getting blocked. I can't seem to fix this issue. Help wanted

**Comment by bgw-teunissen** [comment]
Perchance, we can fix it if we can use the google drive? Because all the data is also downloaded there.

**Comment by Ciertje** [comment]
I build a code that runs now. The only issue could be that its tsv and not csv. However, as far as i can see the read_csv cannot deal properly with whitespace column seperation. Also, our team_members need to be able to advance the assignment.
